[opensearch]
url = "http://localhost:9200"
timeout = 60

[seed]
csv_path = "data/companies_sorted.csv"
index_name = "companies"
batch_size = 500
# row_offset = 0
# row_limit = 1000
# bulk_request_delay = 0.1

[sync]
parquet_path = "data/staged/latest.parquet"
index_name = "companies"
batch_size = 500
soft_delete = false
